# Generated by Django 5.0.4 on 2024-04-30 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0002_remove_athletemodel_slug"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EntryModel",
            new_name="Activities",
        ),
        migrations.RenameModel(
            old_name="AthleteModel",
            new_name="Athletes",
        ),
        migrations.RenameModel(
            old_name="GoalModel",
            new_name="Goals",
        ),
    ]
