# Generated by Django 5.0.4 on 2024-05-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0003_rename_entrymodel_activities_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Logs",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
