# Generated by Django 5.0.4 on 2024-05-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0004_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="logs",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="logs",
            name="status",
            field=models.CharField(default="Success", max_length=10),
            preserve_default=False,
        ),
    ]
