# Generated by Django 5.0.6 on 2024-06-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0005_logs_message_logs_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goals",
            name="month",
            field=models.IntegerField(),
        ),
    ]
