# Generated by Django 5.0.6 on 2024-06-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0006_alter_goals_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goals",
            name="month",
            field=models.PositiveIntegerField(),
        ),
    ]
