# Generated by Django 5.0.6 on 2024-06-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0007_alter_goals_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activities",
            name="ascent",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="activities",
            name="distance",
            field=models.IntegerField(default=0),
        ),
    ]
