# Generated by Django 5.0.6 on 2024-06-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0008_alter_activities_ascent_alter_activities_distance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activities",
            name="moving_time",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="activities",
            name="num_activities",
            field=models.IntegerField(default=1),
        ),
    ]
