# Generated by Django 5.1 on 2024-08-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0009_alter_activities_moving_time_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goals",
            options={"verbose_name": "Tikslas", "verbose_name_plural": "Tikslai"},
        ),
        migrations.AlterField(
            model_name="goals",
            name="hours",
            field=models.PositiveIntegerField(verbose_name="Valandos"),
        ),
        migrations.AlterField(
            model_name="goals",
            name="month",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Sausis"),
                    (2, "Vasaris"),
                    (3, "Kovas"),
                    (4, "Balandis"),
                    (5, "Gegužė"),
                    (6, "Birželis"),
                    (7, "Liepa"),
                    (8, "Rugpjūtis"),
                    (9, "Rugsėjis"),
                    (10, "Spalis"),
                    (11, "Lapkritis"),
                    (12, "Gruodis"),
                ],
                verbose_name="Mėnuo",
            ),
        ),
        migrations.AlterField(
            model_name="goals",
            name="year",
            field=models.PositiveIntegerField(verbose_name="Metai"),
        ),
        migrations.AlterUniqueTogether(
            name="goals",
            unique_together={("year", "month")},
        ),
    ]
