# Generated by Django 5.1 on 2024-08-26 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0010_alter_goals_options_alter_goals_hours_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Goals",
            new_name="Goal",
        ),
    ]
